Repository williamgibb/pyFuckery, pull requests merged in 2019-04, with the labels that each got.

#7 Remove yaml anchors and use a 2.1 config
  .circleci/config.yml
Labels: enhancement

#8 Use fstrings everywhere
  CHANGELOG.rst
  docs/conf.py
  src/fuckery/cli.py
  src/fuckery/constants.py
  src/fuckery/memory.py
  src/fuckery/parser.py
  src/fuckery/vm.py
Labels: enhancement

#9 Fix DeprecationWarning
  CHANGELOG.rst
  src/fuckery/constants.py
Labels: bug

#10 Lark update
  .circleci/config.yml
  CHANGELOG.rst
  setup.py
  src/fuckery/constants.py
  src/fuckery/parser.py
  tests/__init__.py
  tests/common.py
  tests/test_parser.py
  tests/test_pyfuckery.py
  tests/test_vm.py
Labels: enhancement

#11 Msgpack makes fuckery go vroom vroom fast
  CHANGELOG.rst
  setup.py
  src/fuckery/memory.py
  src/fuckery/vm.py
Labels: enhancement

#4 Fixed a broken badge, and removed a broken badge
  README.rst
Labels: help wanted
